import React from 'react';
import type { Metadata } from 'next';
import './global.css';
import { fontInter } from '../fonts/inter';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';
import Navbar from '@/components/navbar/Navbar';
import Providers from './providers/Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode;
  authModal: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body
        className={cn(fontInter.variable, 'bg-white to-slate-900 antialiased')}
      >
        <Providers>
          <Navbar />
          {authModal}
          <div className="container max-w-7xl mx-auto h-full pt-16">
            {children}
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
