import React from 'react';
import type { Metadata } from 'next';
import './globals.css';
import { fontInter } from '../fonts/inter';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body
        className={cn(
          fontInter.variable,
          'bg-white to-slate-900 antialiased',
        )}
      >
        {children}
      </body>
    </html>
  );
}
