import React from 'react';
import type { Metadata } from 'next';
import './global.css';
import { fontInter } from '../fonts/inter';
import { cn } from '@/lib/utils';
import Navbar from '@/components/navbar/Navbar';
import Toaster from '@/components/Toaster';
import QueryProvider from '../providers/Providers';

export const metadata: Metadata = {
  title: 'qTalk',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode;
  authModal: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body
        className={cn(fontInter.variable, 'bg-slate-50 text-slate-900 antialiased light')}
      >
        <QueryProvider>
          <Navbar />
          {authModal}
          <div className="container max-w-7xl mx-auto h-full pt-16">
            {children}
          </div>
        </QueryProvider>
        <Toaster/>
      </body>
    </html>
  );
}
